gallery/urls.py
from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [
    path('gallery/<str:section_slug>/', views.pin_list.as_view(), name='showcase'),
    path('gallery/', views.section_list.as_view(), name='list sections'),
    path('boards/', views.create_boards, name='create boards'),
    path('sections/', views.create_sections, name='create sections'),
    path('pins/', views.create_pins, name='create pins'),
]

pinlery/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
import gallery.urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path(r'', include(gallery.urls)),
]

gallery/models.py
from django.db import models
import uuid
from django.db.models import signals
from django.dispatch import receiver
from django.template.defaultfilters import slugify


# Create your models here.
class Profile(models.Model):
    id_pinterest = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        editable=False
    )
    username = models.CharField(
        max_length=25,
        default='pinterest',
        blank=False
    )
    full_name = models.CharField(
        max_length=40,
        default='',
        blank=True
    )
    listed_website_url = models.CharField(
        max_length=40,
        default="",
        blank=True
    )
    image_url = models.CharField(
        max_length=200,
        default='',
        blank=True
    )
    follower_count = models.IntegerField(
        default=0
    )
    following_count = models.IntegerField(
        default=0
    )
    active = models.BooleanField(
        blank=False,
        default=False,
        editable=True
    )

    def __str__(self):
        return self.username

    def save(self, *args, **kwargs):
        from pinlery.init_api import Pinterest

        profile = Pinterest().get_user_overview(username=self.username)
        self.follower_count = profile['follower_count']
        self.following_count = profile['following_count']
        self.listed_website_url = str(profile['listed_website_url'])
        self.image_url = profile['image_medium_url']
        self.full_name = '{} {}'.format(profile['first_name'], profile['last_name'])
        self.id_pinterest = int(profile['id'])
        super().save(*args, **kwargs)


class Board(models.Model):
    id_pinterest = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        editable=False
    )
    title = models.CharField(
        max_length=200
    )
    slug = models.SlugField(
        default='',
        editable=False,
        max_length=200,
    )
    user = models.ForeignKey(
        to=Profile,
        on_delete=models.CASCADE,
        default=''
    )
    active = models.BooleanField(
        blank=False,
        default=False
    )

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        value = self.title
        self.slug = slugify(value)
        super().save(*args, **kwargs)


class Section(models.Model):
    id_pinterest = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        editable=False
    )
    title = models.CharField(
        max_length=200,
        default=''
    )
    slug = models.SlugField(
        max_length=200,
        default=''
    )
    active = models.BooleanField(
        blank=False,
        default=False
    )
    board = models.ForeignKey(
        to=Board,
        default='',
        on_delete=models.CASCADE
    )

    def title_custom_split(self):
        return self.title.replace('[ ', '').split(' ] ')

#    def slug_custom_split(self):
#        return self.title.replace('[ ', '').split(' ] ')[0].replace(' ', '-').lower()

    def save(self, *args, **kwargs):
        value = self.title.replace('[ ', '').split(' ] ')[0]
        self.slug = slugify(value)
        super().save(*args, **kwargs)

    def __str__(self):
        return "{} | {}".format(
            self.board.title,
            self.title
        )


class Pin(models.Model):
    id_pinterest = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        editable=False
    )
    title = models.CharField(
        max_length=200,
        default=""
    )
    description = models.CharField(
        max_length=200,
        default=""
    )
    section = models.ForeignKey(
        to=Section,
        on_delete=models.CASCADE
    )
    image_url = models.CharField(
        max_length=200,
        default=""
    )
    height = models.PositiveIntegerField(
        default=0
    )
    width = models.PositiveIntegerField(
        default=0
    )
    small_image_url = models.CharField(
        max_length=200,
        default=""
    )
    height_s = models.PositiveIntegerField(
        default=0
    )
    width_s = models.PositiveIntegerField(
        default=0
    )
    medium_image_url = models.CharField(
        max_length=200,
        default=""
    )
    height_m = models.PositiveIntegerField(
        default=0
    )
    width_m = models.PositiveIntegerField(
        default=0
    )
    sort_position = models.PositiveIntegerField(
        default=0
    )
    color = models.CharField(
        max_length=8,
        default="#ffffff"
    )

    def __str__(self):
        pin_title = ""
        if len(self.title) < 2 and len(self.description) < 2:
            pin_title = "Untitled"
        elif len(self.title) < 2:
            pin_title = self.description[0:27]
        else:
            pin_title = self.title
        return "{} | {} | {}".format(
            self.section.board.title,
            self.section.title,
            pin_title
        )


class SectionDescription(models.Model):
    description = models.TextField(
        max_length=1500,
        blank=True,
        default=""
    )
    section = models.OneToOneField(
        'Section',
        on_delete=models.SET_NULL,
        null=True
    )

    def __str__(self):
        try:
            return self.section.title
        except AttributeError:
            return self.description[0:100]

gallery/forms.py
from django import forms


class ProfileForm(forms.Form):
    username = forms.CharField(label='Target board username', max_length=26)

gallery/views.py
# -*- coding: utf-8 -*-
from django.shortcuts import render, redirect
from django.db import IntegrityError
from django.contrib import messages
import os
from django.views.generic import ListView
from django.core.paginator import Paginator
from django.shortcuts import get_object_or_404
from django.contrib.auth.decorators import user_passes_test
from .models import Board, Section, Pin, Profile


class pin_list(ListView):
    model = Pin
    template_name = "gallery/pages/showcase.html"
    active_sections = Section.objects.filter(active=True)
    context_object_name = 'pins'
    paginate_by = 9

    def get_queryset(self):
        self.section = get_object_or_404(Section, slug=self.kwargs.get("section_slug"))
        pins = Pin.objects.filter(section=self.section)
        self.pins_count = Pin.objects.filter(section=self.section).count()
        return pins

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['menu_description'] = '{} {} {}'.format('About', self.pins_count, 'items')
        context['active_sections'] = self.active_sections.exclude(slug=self.section.slug)
        context['paginate_limit'] = [3, -3]
        context['section'] = self.section
        return context


class section_list(ListView):
    model = Section
    queryset = Section.objects.filter(active=True)
    context_object_name = 'section_list'
    template_name = "gallery/pages/section_list.html"
    paginate_by = 6

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        count = context['section_list'].count()
        context['menu_description'] = '{} {} {}'.format('There is', count, 'personal art galleries on')
        return context


@user_passes_test(lambda u: u.is_superuser)
def create_boards(request):
    from pinlery.init_api import Pinterest
    active_users = Profile.objects.filter(active=True)
    for user in active_users:
        pinterest = Pinterest(username=user.username)
        boards = pinterest.get_user_boards()
        while boards:
            for board in boards:
                target_board_id = int(board['id'])
                new_board = Board(title=board['name'],
                                  user=user,
                                  id_pinterest=target_board_id)
                try:
                    new_board.save()
                except IntegrityError:
                    continue
            boards = pinterest.get_user_boards()
    return redirect('/admin/gallery/board')


@user_passes_test(lambda u: u.is_superuser)
def create_sections(request):
    from pinlery.init_api import Pinterest
    pinterest = Pinterest()
    active_boards = Board.objects.filter(active=True)
    for board in active_boards:
        target_board_id = str(int(board.id_pinterest))
        sections = pinterest.get_board_sections(board_id=target_board_id)
        while sections:
            for section in sections:
                section_id = int(section['id'])
                new_section = Section(title=section['title'], id_pinterest=section_id, board=board, slug=section["slug"])
                try:
                    new_section.save()
                except IntegrityError:
                    continue
            sections = pinterest.get_board_sections(board_id=target_board_id, reset_bookmark=True)

    return redirect('/admin/gallery/section')


@user_passes_test(lambda u: u.is_superuser)
def create_pins(request):
    from pinlery.init_api import Pinterest
    pinterest = Pinterest()
    active_sections = Section.objects.filter(active=True, board__active=True)
    for section in active_sections:
        target_section_id = str(int(section.id_pinterest))
        pins = pinterest.get_section_pins(section_id=target_section_id)
        counter = 0
        while pins:
            for pin in pins:
                pin_id = int(pin['id'])
                new_pin = Pin(id_pinterest=pin_id,
                              title=pin["title"],
                              description=pin["description"],
                              section=section,
                              image_url=pin["images"]["orig"]["url"],
                              width=pin["images"]["orig"]["width"],
                              height=pin["images"]["orig"]["height"],
                              small_image_url=pin["images"]["236x"]["url"],
                              width_s=pin["images"]["236x"]["width"],
                              height_s=pin["images"]["236x"]["height"],
                              medium_image_url=pin["images"]["736x"]["url"],
                              width_m=pin["images"]["736x"]["width"],
                              height_m=pin["images"]["736x"]["height"],
                              color=pin['dominant_color'],
                              sort_position=counter)
                counter += 1
                try:
                    new_pin.save()
                except IntegrityError:
                    counter += 1
                    continue
            pins = pinterest.get_section_pins(section_id=target_section_id, reset_bookmark=True)

    return redirect('/admin/gallery/pin')

gallery/templates/gallery/pages/section_list.html
{% extends 'gallery/base.html' %}
{% load static %}

{% block static_CSS %}
    {% include 'gallery/partials/imports/import-static-css.html' %}
{% endblock %}

{% block page_styles %}
    <link rel="stylesheet" type="text/css" href="{% static '/gallery/css/pages/grid_section_list.css' %}">
{% endblock %}

{% block navigation %}
    {% include 'gallery/partials/elements/nav-bar.html' %}
{% endblock %}

<!-- main -->
{% block content %}
    <div class="container">
        <div class="masonry-grid row-grid row-cols-lg-3 row-cols-md-3 row-cols-xs-1">
            {% if section_list %}
                {% for section in section_list %}
                    <div class="masonry-grid-item col-lg-4 col-md-4 col-xs-11">
                        <div class="border border-light card bg-primary bg-1 shadow">
                            <div class="text-black rounded text-center p-3 mt-4">
                                <a class="" href="{% url 'showcase' section.slug %}">
                                    <h3 class="p-0 mb-0">{{ section.title_custom_split.0 }}</h3>
                                    <span class="text-gray m-1">{{ section.title_custom_split.1 }}</span>
                                </a>
                            </div>
                            <div class="row mr-4 ml-4 p-1 mb-3">
                                {% for pin in section.pin_set.all|slice:":2" %}
                                    <div class="col-6">
                                        <a data-fancybox="collection" data-options='{
                                        "caption":"<a href=\"{% url 'showcase' section.slug %}\">{{ section.title }}<br>Touch to enter the entire collection!</a>",
                                        "src":"{{ pin.image_url }}", "link":"{% url 'showcase' section.slug %}", "clickContent" : false, "idleTime": false,
                                        "buttons": ["slideShow","thumbs","close"]}'>
                                            <img src="{{ pin.small_image_url }}" alt="" class="image shadow-lg rounded d-block">
                                        </a>
                                    </div>
                                {% endfor %}
                            </div>

                            <div class="post-meta border border-light rounded bg-2 p-2 m-2">
                                <div class="row">
                                    <div class="col-3">
                                        <span class="badge badge-lg shadow-inset">
                                            <b class="">
                                                <span aria-hidden="true" class="far fa-heart "></span>
                                                {{ section.pin_set.all|length }}
                                            </b>
                                        </span>
                                    </div>
                                    <div class="col-9 text-right">
                                        <button class="btn btn-sm btn-icon-only btn-primary btn-pill text-danger mr-2 bg-1" type="button">
                                            <span aria-hidden="true" class="far fa-heart"></span>
                                        </button>
                                        <button class="btn btn-sm btn-icon-only btn-primary btn-pill text-gray bg-1 " type="button">
                                            <span aria-hidden="true" class="far fa-heart"></span>
                                        </button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            {% endif %}
        </div>
        </div>
{% endblock %}

{% block menu %}
    {% include 'gallery/partials/elements/menu.html' with mode='section_list' %}
{% endblock %}

{% block static_JS %}
    {% include 'gallery/partials/imports/import-static-js.html' %}
{% endblock %}

{% block page_scripts %}
    {% include 'gallery/partials/scripts/script_init_fancybox.html' with mode='section_list' only %}
{% endblock %}

gallery/templates/gallery/pages/showcase.html
{% extends 'gallery/base.html' %}
{% load static %}

{% block static_CSS %}
    {% include 'gallery/partials/imports/import-static-css.html' %}
{% endblock %}

{% block page_styles %}
    <link rel="stylesheet" type="text/css" href="{% static '/gallery/css/fancybox_animation.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static '/gallery/css/pages/skeuomorphic_frame.css' %}">
{% endblock %}

{% block navigation %}
    {% include 'gallery/partials/elements/nav-bar.html' %}
{% endblock %}

<!-- main -->
{% block content %}
    <div class="container">
        <div class="flex-row m-0 p-0">
            <div class="text-center jumbotron bg-primary m-0 pb-1 pt-5">
                <h1 class="badge badge-pill badge-primary text-gray text-uppercase"><b> {{ section.board.title }}</b></h1>
                <h1>
                    {{ section.title }}
                </h1>
                    <ul class="pagination circle-pagination pagination-sm justify-content-center">
                        {% if page_obj.number > paginate_limit.0 %}
                            <li class="page-item">
                                <a class="page-link" href="?page=1">
                                    <i class="fas fa-angle-double-left"></i>
                                </a>
                            </li>
                        {% endif %}
                        {% for i in page_obj.paginator.page_range %}
                            {% if page_obj.number == i %}
                                <li class="page-item active disabled">
                                    <a class="page-link rounded" href="#">
                                        <b>{{ i }}</b>
                                        <span class="sr-only">current</span>
                                    </a>
                                </li>
                            {% elif i > page_obj.number|add:'-3' and i < page_obj.number|add:'3' %}
                                <li class="page-item">
                                    <a class="page-link rounded" href="?page={{ i }}">
                                        <b>{{ i }}</b>
                                    </a>
                                </li>
                            {% endif %}
                        {% endfor %}
                        {% if page_obj.number <= page_obj.paginator.num_pages|add:paginate_limit.1 %}
                            <li class="page-item">
                                <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">
                                        <i class="fas fa-angle-double-right"></i>
                                </a>
                            </li>
                        {% endif %}
                    </ul>
            </div>
        </div>
        <div class="masonry-grid row-grid">
           {% for pin in pins %}
               <div class="masonry-grid-item col-xs-11 col-md-6 col-lg-4 p-3">
                   <div class="shadow-soft border-0 d-block">
                           <a data-fancybox="{{ section.slug }}"
                              data-type="image"
                              href="{{ pin.image_url }}"
                              data-caption="{{ pin.title }}"
                              class="frame">
                       <figure class="imageWrapper" style="background-color:{{ pin.color }}">
                               <img data-srcset="{{ pin.medium_image_url }}"
                                    width="{{ pin.width_m }}"
                                    height ="{{ pin.height_m }}"
                                    alt="{{ pin.title }}"
                                    class="image lazy d-block"
                                    style="color: white"/>
                       </figure>
                           </a>
                   </div>
               </div>
           {% endfor %}
        </div>
    </div>
{% endblock %}

{% block menu %}
    {% include 'gallery/partials/elements/menu.html' with mode="showcase" %}
{% endblock %}

{% block static_JS %}
    {% include 'gallery/partials/imports/import-static-js.html' %}
{% endblock %}

{% block page_scripts %}
    {% include 'gallery/partials/scripts/script_init_fancybox.html' with mode='fullscreen' section_slug=section.slug only %}
{% endblock %}